{% set version = "2.17-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-openair
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/openair_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/openair/openair_{{ version }}.tar.gz
  sha256: b81cf34075dc9db914a3c980262d52b26f27b14421411b5befab88bc95897caf

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-rcpp
    - r-cluster
    - r-dplyr >=1.0
    - r-hexbin
    - r-lattice
    - r-latticeextra
    - r-lubridate
    - r-mapproj
    - r-mgcv
    - r-purrr
    - r-readr
    - r-rlang
    - r-tidyr
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass
    - r-rcpp
    - r-cluster
    - r-dplyr >=1.0
    - r-hexbin
    - r-lattice
    - r-latticeextra
    - r-lubridate
    - r-mapproj
    - r-mgcv
    - r-purrr
    - r-readr
    - r-rlang
    - r-tidyr

test:
  commands:
    - $R -e "library('openair')"           # [not win]
    - "\"%R%\" -e \"library('openair')\""  # [win]

about:
  home: https://davidcarslaw.github.io/openair/
  dev_url: https://github.com/davidcarslaw/openair
  license: GPL-2.0-or-later
  summary: Tools to analyse, interpret and understand air pollution data. Data are typically hourly time series and both monitoring data and dispersion model output can be analysed.  Many functions can also be applied to other data, including meteorological and traffic data.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
